### ISSUE TITLE
"latest" does not seem to work

### ISSUE THREAD

**Issue by JayFoxRox** [er28-0652/setup-ghidra#14]
I tried using ["latest" in a workflow in ghidra-emotionengine](https://github.com/JayFoxRox/ghidra-emotionengine/actions/runs/908923000/workflow#L10), but [it does not work:](https://github.com/JayFoxRox/ghidra-emotionengine/runs/2752272196?check_suite_focus=true)

```
Run er28-0652/setup-ghidra@master
  with:
    version: latest
  env:
    JAVA_HOME_11.0.11_x64: /opt/hostedtoolcache/jdk/11.0.11/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.11/x64
    JAVA_HOME_11_0_11_X64: /opt/hostedtoolcache/jdk/11.0.11/x64
(node:1706) UnhandledPromiseRejectionWarning: Error: versionSpec parameter is required
    at Object.find (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:5946:17)
    at Object.<anonymous> (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:3450:31)
    at step (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:3281:27)
    at Object.next (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:3218:22)
    at /home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:3188:72
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:3167:18)
    at Object.installGhidra (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:3438:16)
    at /home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:6402:27
    at step (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:6369:27)
(node:1706) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1706) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by er28-0652** [comment]
Can you try with version `0.0.5` again? thank you!
