### ISSUE TITLE
Fails with new Ghidra 10 Release

### ISSUE THREAD

**Issue by fmagin** [er28-0652/setup-ghidra#15]
Using the action with
```
      - uses: er28-0652/setup-ghidra@master
        with:
                version: "10.0"
```
for the 10.0 release that came out today, seems to fail with:

```
Run er28-0652/setup-ghidra@master
  with:
    version: 10.0
  env:
    JAVA_HOME_11.0.11_x64: /opt/hostedtoolcache/jdk/11.0.11/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.11/x64
    JAVA_HOME_11_0_11_X64: /opt/hostedtoolcache/jdk/11.0.11/x64
Error: 649) UnhandledPromiseRejectionWarning: Error: [ERROR] 10.0 is not found.
    at Object.<anonymous> (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:3472:25)
    at step (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:3281:27)
    at Object.next (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:3218:22)
    at fulfilled (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:3170:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1649) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1649) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by er28-0652** [comment]
sorry for late reply. it's because NSA has changed download URL from `ghidra-sre.org` to github, which `setup-ghidra` hadn't supported. I update `setup-ghidra` to download archive from github from version `0.0.5`. can you try with `0.0.5` again?

**Comment by fmagin** [comment]
Yeah, they changed the link, in the repo where I urgently needed it I just used my fork with directLink support to workaround this (by directly linking the correct release). Just bumped the version in some other project to see if it works https://github.com/fmagin/ghidra-minesweeper/pull/2

**Comment by fmagin** [comment]
Still seems to fail though (with `10.0.1`):

```
Run er28-0652/setup-ghidra@master
  with:
    version: 10.0.1
    directLink: None
  env:
    JAVA_HOME_11.0.12_x64: /opt/hostedtoolcache/jdk/11.0.12/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.12/x64
    JAVA_HOME_11_0_12_X64: /opt/hostedtoolcache/jdk/11.0.12/x64
Version: 10.0.1, URL: None
Invalid URL: None
Waiting 13 seconds before trying again
Invalid URL: None
Waiting 15 seconds before trying again
(node:2100) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: None
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at HttpClient.request (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:10872:27)
    at HttpClient.get (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:10759:23)
    at /home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:11430:39
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:11321:72
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:11300:18)
    at downloadToolAttempt (/home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:11415:16)
(node:2100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:2100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by er28-0652** [comment]
it seems it's because the default value (`None`) for `directLink`. this script received `None` as string and recognized it as directLink, then failed. 

I updated the default value in the commit https://github.com/er28-0652/setup-ghidra/commit/b53614dada0a16e3c342277caae905b96d803109, which is included in version `0.0.6`. can you try it with latest version again? thank you!

**Comment by fmagin** [comment]
seems to work now https://github.com/fmagin/ghidra-minesweeper/runs/3137373715 !

**Comment by er28-0652** [comment]
great! thank you for testing! I'm closing this issue.
