### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError: API rate limit exceeded

### ISSUE THREAD

**Issue by fmagin** [er28-0652/setup-ghidra#19]
I just ran into this error:

```
Run er28-0652/setup-ghidra@master
  with:
    version: 10.1
  env:
    JAVA_HOME_11.0.13_x64: /opt/hostedtoolcache/jdk/11.0.13/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.13/x64
    JAVA_HOME_11_0_13_X64: /opt/hostedtoolcache/jdk/11.0.13/x64
(node:1746) UnhandledPromiseRejectionWarning: HttpError: API rate limit exceeded for 40.85.181.4. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at /home/runner/work/_actions/er28-0652/setup-ghidra/master/dist/index.js:4580:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1746) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1746) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This can be addressed with the PR https://github.com/er28-0652/setup-ghidra/pull/17 which allows using authenticated requests, but what I also consider a minor issue here is that the setup-ghidra action still reports _success_ and the CI only fails one step later when I actually try to build the extension and get a:
```
A problem occurred evaluating project ':GhidraJupyterKotlin'.
> GHIDRA_INSTALL_DIR is not defined!
```

**Comment by antoniovazquezblanco** [comment]
I have published an updated version of this action that includes this feature: https://github.com/antoniovazquezblanco/setup-ghidra.
